name: conda-presto-streamlit
channels:
  - conda-forge
dependencies:
  - python >=3.13,<3.14
  - streamlit
  - conda >=25.3
  - conda-rattler-solver >=0.0.6,<0.0.7
  - conda-lockfiles >=0.1.1
  - pyyaml >=6.0
  - msgspec >=0.19
  - litestar >=2.18
  - pyjwt >=2.0
  - uvicorn >=0.34
  - brotli-python >=1.1
  - httpx >=0.28
  - pip
  - pip:
      - -e .
